### ISSUE TITLE
[Suggestion] Count Wilderness as a place to apply ClaimTweaks

### ISSUE THREAD

**Issue by fatyg5** [Eufranio/ClaimTweaks#1]
Allow wilderness to run ClaimTweak commands.

The practical implication for this is the idea that, if you want all your player claims to have /fly inside of them, but when leaving, the wilderness toggles /fly, you can do so. Right now, you'd have to set every player claim to do this, but by allowing wilderness to use ClaimTweaks, you only have to set it once.

**Comment by Eufranio** [comment]
Try with the latest version: https://ore.spongepowered.org/Eufranio/ClaimTweaks/versions/2.0
