### ISSUE TITLE
ERROR: [io.github.eufranio.claimtweaks.config.ConfigManager:load:59]

### ISSUE THREAD

**Issue by Champion0912** [Eufranio/ClaimTweaks#5]
Hi, I am getting the following error:
https://pastebin.com/45RLfbUb

I am using the (currently) latest Spongeforge, Bungeecord, GriefPrevention, PackectGate, together with 61 different mods and plugins.
What additional info do you need to resolve this one?

**Comment by Eufranio** [comment]
Which SpongeForge version? This was already fixed by Sponge some time ago.

**Comment by Champion0912** [comment]
My apologies, seems like the test-server (on which I installed ClaimTweaker) was not up to date on sponge forge. Now running smoothly with build 3361 👍

**Comment by Eufranio** [comment]
Great!
